#!/usr/bin/env bash
set -euo pipefail

CONTAINER_ID=

start_docker_compose() {
    echo "Starting Docker Compose..."
    docker compose up -d

    CONTAINER_ID=$(docker compose ps -q r-env)
    if [ -z "$CONTAINER_ID" ]; then
        echo "Error: Could not find the container ID for the 'r-env' service." >&2
        exit 1
    fi
    echo "Docker container ID for 'r-env' service: $CONTAINER_ID"
}

kill_docker_container() {
    echo "Killing Docker Container..."
    docker kill $CONTAINER_ID
}

install_packages_in_container() {
    echo "Install packages in the Docker container"
    docker exec "$CONTAINER_ID" ./make install-package
}

run_r_in_container() {
    echo "Running main.R in the Docker container..."
    docker exec "$CONTAINER_ID" ./make run main.R
}

start_docker_compose
install_packages_in_container
run_r_in_container
kill_docker_container
